##Lab 2 - Implement Tensors and Tensor Operations – Slicing, Broadcasting and Reshaping ##

In [1]:
from keras.datasets import mnist
import numpy as np
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


##Tensor Slicing Example 1:

In [2]:
train_images.shape
slice_images = train_images[15]
# Select the 15th image from the dataset of 60,000 images
slice_images.shape

(28, 28)

In [3]:
# Selecting all images from 10th upto 100th (90 images)
slice_images = train_images[10:100]
slice_images.shape

(90, 28, 28)

In [4]:
# this is equivalent to previous code
slice_images = train_images[10:100,0:28, 0:28]
slice_images.shape

(90, 28, 28)

**Tensor Slicing - Exercise 1: Apply tensor slicing to get the 18 x 18 pixels from the bottom right corner of all images**

In [5]:
slice_images = train_images[:,10:28,10:28]
slice_images.shape

(60000, 18, 18)

**Tensor Slicing - Exercise 2: Apply tensor slicing to get the 18 x 18 pixels from the middle of all images**

In [6]:
slice_images = train_images[:,5:23,5:23]
slice_images.shape

(60000, 18, 18)

**Tensor Slicing - Exercise 3:  Apply tensor slicing to select first three batches of images. Assume batch-size of 128**

In [7]:
slice_images = train_images[0:128,:,:]
slice_images.shape

(128, 28, 28)

In [8]:
slice_images = train_images[128:256,:,:]
slice_images.shape

(128, 28, 28)

In [9]:
slice_images = train_images[256:384,:,:]
slice_images.shape

(128, 28, 28)

**Exercise 4: Try to generalize the selection of batches such that if asked to get nth batch your generalized code can fetch the same. Assume
that you get the batch# as a parameter**

The smaller tensor is usually broadcasted to match the shape of the larger tensor. Broadcasting consists of two steps:
1. Axes are added to the smaller tensor to match the ndim of the larger tensor.
2. The smaller tensor is repeated along-side the new axes to match the full shape of the larger tensor

In [10]:
n = 2
slice_images = train_images[128*n:128*(n+1)]
slice_images.shape

(128, 28, 28)

##Topic 2 - Understanding Broadcasting##

In [11]:
# Example 1 - Successful Broadcasting
# x is a 1 D tensor with shape (4,)
x = np.array([1,4,6,9])
x.ndim

1

In [12]:
x.shape

(4,)

In [13]:
# y is a matrix (i.e., a 2-D tensor) with shape (3,4)
y = np.array([
    [24,57,96,99],
    [35,14,75,89],
    [15,26,49,72]
    ])
y.ndim

2

In [14]:
y.shape

(3, 4)

In [15]:
# They are actually not compatible for tensor operation of addition
# However because of implicit broadcasting the shape of the smaller tensor x will be matched with shape of y
x + y # successful because of broadcasting. Here due to broadcasting x is considered as:
# [[1,4,6,9],
# [1,4,6,9],
# [1,4,6,9]] for the tensor operation
np.array([
    [24,57,96,99],
    [35,14,75,89],
    [15,26,49,72]
    ])

array([[24, 57, 96, 99],
       [35, 14, 75, 89],
       [15, 26, 49, 72]])

In [16]:
x.shape

(4,)

In [17]:
# Example 2 - Illustrating how broadcasting might fail in certain cases
# If the shape of tensors cannot be made compatible through broadcasting you will get an error
p = np.array([1,2,3,4,5])
q = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]
])

In [18]:
# Here the smaller tensor p has shape (5,)
# The larger tensor q has shape (3,4)
# Thus they cannot be made compatible even through broadcasting.
# Therefore we get error when we try to add them as seen below:
p + q

ValueError: ignored

Reshaping a tensor means rearranging the elements in the tensor or rearranging its rows and columns to match a target shape.
The reshaped tensor has the same no of elements as the original tensor.
Below are some simple examples of tensor reshaping:

In [19]:
x = np.array([[1,2,3],
              [4,5,6]
              ])
x.shape

(2, 3)

In [20]:
x = x.reshape((6,1))
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
# Transpose operation is an example of reshaping
x = np.array([[1,2,3],
              [4,5,6]
            ])
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
x = np.transpose(x)
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
x.shape

(3, 2)